### ISSUE TITLE
태그 및 라벨에서 `color`를 key로 사용할지에 대해

### ISSUE THREAD

**Issue by high2092** [boostcampwm-2022/web19-Boostart#54]
#### `color`를 key로 사용할 경우
- 한 유저에 대해 같은 title을 가진 태그(혹은 라벨)가 여러 개 존재할 수 있습니다.

#### `color`를 key로 사용하지 않을 경우
- 한 유저에 대해 같은 title을 가진 태그(혹은 라벨)가 한 개만 존재할 수 있습니다.

#### + count 컬럼 추가 ( 최근 조회된 태그 순 정렬을 위해 )

**Comment by mikaniz** [comment]
데일리 스크럼에서 논의한 결과
1. `(user_idx, title)`에 `unique` 제약 사항을 추가하기로 결정 → DB 반영 완료
2. 태그에 속한 태스크의 개수를 뜻하는 `count`의 경우 컬럼을 추가하지 않고 `JOIN`을 이용하여 계산하기로 결정
